#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright © 1998 - 2025 Tencent. All Rights Reserved.
###########################################################################
"""
Author: Tencent AI Arena Authors
"""


class Config:

    # Observation and action shapes
    DIM_OF_OBSERVATION = 32
    DIM_OF_ACTION_PHASE_1 = 4
    DIM_OF_ACTION_DURATION_1 = 4
    DIM_SUB_ACTION_MASK = 24
    NUMB_HEAD = 2

    GRID_WIDTH = 14
    GRID_NUM = 20
    GRID_LENGTH = 5
    MAX_GREEN_DURATION = 40
    MAX_RED_DURATION = 60
    DURATION_TO_SECONDS = [5, 10, 15, 20]

    # Delay-pressure controller
    CLOSE_DISTANCE = 120.0
    VERY_CLOSE_DISTANCE = 40.0
    APPROACH_PRESSURE_COEF = 0.9
    CLOSE_PRESSURE_COEF = 1.6
    VERY_CLOSE_PRESSURE_COEF = 1.1
    QUEUE_PRESSURE_COEF = 2.2
    WAIT_PRESSURE_COEF = 0.85
    VEHICLE_PRESSURE_COEF = 0.35
    DELAY_PRESSURE_COEF = 2.1
    LANE_QUEUE_PRESSURE_COEF = 1.2
    CONGESTION_PRESSURE_COEF = 1.1
    OPEN_LANE_BONUS_COEF = 0.2
    IDLE_BONUS_COEF = 0.55
    MAX_IDLE_ROUNDS = 3
    MIN_PHASE_HOLD_ROUNDS = 2
    MAX_PHASE_HOLD_ROUNDS = 3
    KEEP_SCORE_MARGIN = 0.9
    KEEP_SCORE_RATIO = 0.9
    STARVATION_OVERRIDE_RATIO = 0.84
    KEEP_PHASE_BONUS = 0.18
    MIN_SWITCH_DURATION_ACTION = 1
    RULE_PHASE_BIAS_SCALE = 0.95
    RULE_SELECTED_PHASE_BONUS = 0.4
    RULE_DURATION_BIAS = 0.5
    BLOCKED_PHASE_BIAS_PENALTY = 0.12
    MAX_WAIT_PRESSURE_COEF = 0.28
    BLOCKED_PHASE_PENALTY = 1.6
    MIN_ACTIVE_WEIGHT = 0.4
    BLOCKED_LANE_ACCIDENT_NEAR_LEVEL = 1.0
    BLOCKED_LANE_ACCIDENT_FAR_LEVEL = 0.7
    BLOCKED_LANE_IRREGULAR_NEAR_LEVEL = 0.45
    BLOCKED_LANE_IRREGULAR_FAR_LEVEL = 0.2
    HIGH_BLOCKED_RATIO = 0.55
    HARD_BLOCKED_RATIO = 0.80
    PHASE_SCORE_GAP_HIGH = 6.0
    PRESSURE_HIGH_THRESHOLD = 42.0
    PRESSURE_MID_THRESHOLD = 24.0
    PRESSURE_LOW_THRESHOLD = 8.0
    SOTL_MIN_GREEN_PRESSURE = 6.0
    SOTL_KEEP_GREEN_PRESSURE = 7.0
    SOTL_RED_PRESSURE_MARGIN = 2.5
    SOTL_FORCE_SWITCH_RATIO = 1.08
    SOTL_FORCE_SWITCH_GAP = 2.5
    FORCE_SWITCH_PRESSURE_GAP = 2.5
    FORCE_SWITCH_IDLE_ROUNDS = 3

    # Observation normalization
    OBS_CLOSE_NORM = 12.0
    OBS_QUEUE_NORM = 24.0
    OBS_DELAY_NORM = 15.0
    OBS_VEHICLE_NORM = 18.0
    OBS_MAX_WAIT_NORM = 60.0
    OBS_PHASE_SCORE_NORM = 70.0
    OBS_TOTAL_CLOSE_NORM = 16.0
    OBS_SCENE_WAITING_NORM = 300.0
    OBS_SAME_PHASE_NORM = 8.0
    OBS_SCORE_GAP_NORM = 18.0

    # Duration thresholds
    PHASE_MAX_WAIT_HIGH = 28.0
    PHASE_MAX_WAIT_MID = 18.0
    PHASE_MAX_WAIT_LOW = 9.0
    PHASE_LANE_QUEUE_HIGH = 16.0
    PHASE_LANE_QUEUE_MID = 9.0
    PHASE_LANE_QUEUE_LOW = 4.0
    HIGH_SCENE_WAITING_THRESHOLD = 220.0
    EMERGENCY_SCENE_WAITING_THRESHOLD = 210.0
    EMERGENCY_MAX_WAIT_THRESHOLD = 38.0
    BLOCKED_PHASE_MAX_DURATION_ACTION = 1
    IRREGULAR_RISK_MIN_DURATION_ACTION = 2

    # Hard robustness
    WAIT_TIME_CAP = 60.0
    ACCIDENT_CLOSE_DISTANCE = 25.0
    IRREGULAR_RISK_PRESSURE_COEF = 1.8
    IRREGULAR_CLOSE_PRESSURE_COEF = 1.4

    # Reward shaping
    REWARD_TOTAL_WAIT_COEF = 0.5
    REWARD_QUEUE_COEF = 0.8
    REWARD_CLOSE_COEF = 0.45
    REWARD_DELAY_COEF = 1.6
    REWARD_MAX_WAIT_COEF = 0.65
    REWARD_SCENE_WAITING_COEF = 0.35
    REWARD_THROUGHPUT_COEF = 0.8
    REWARD_RISK_COEF = 1.2
    REWARD_TOTAL_WAIT_CLIP = 10.0
    REWARD_QUEUE_CLIP = 6.0
    REWARD_CLOSE_CLIP = 6.0
    REWARD_DELAY_CLIP = 6.0
    REWARD_MAX_WAIT_CLIP = 12.0
    REWARD_SCENE_WAITING_CLIP = 18.0
    MAX_WAIT_PENALTY_THRESHOLD = 28.0
    MAX_WAIT_PENALTY_COEF = 0.12
    SCENE_WAITING_RISK_THRESHOLD = 210.0
    SCENE_WAITING_RISK_DIVISOR = 20.0
    SWITCH_PENALTY = 0.12
    EMPTY_ROAD_BONUS = 0.2

    # PPO training parameters
    INIT_LEARNING_RATE_START = 0.001
    BETA_START = 0.01
    LOG_EPSILON = 1e-6
    RMSPROP_DECAY = 0.9
    RMSPROP_MOMENTUM = 0.0
    RMSPROP_EPSILON = 0.01
    CLIP_PARAM = 0.2
    MIN_POLICY = 0.00001
    LABEL_SIZE_LIST = [DIM_OF_ACTION_PHASE_1, DIM_OF_ACTION_DURATION_1]
    LEGAL_ACTION_SIZE_LIST = LABEL_SIZE_LIST.copy()
    IS_REINFORCE_TASK_LIST = [True] * NUMB_HEAD
    EVAL_FREQ = 5
    GAMMA = 0.995
    LAMDA = 0.95
    USE_GRAD_CLIP = False
    GRAD_CLIP_RANGE = 0.9
    VALUE_COEF = 1
